# Generated by Django 5.1 on 2025-07-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=10)),
                ('email_id', models.EmailField(max_length=254)),
                ('address', models.TextField(blank=True)),
                ('position', models.CharField(max_length=100)),
            ],
        ),
    ]
