# Generated by Django 5.1 on 2025-07-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_dealership', '0003_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='worker_id',
            field=models.CharField(default='WRK-001', max_length=100, unique=True),
        ),
    ]
